
set NewFontsDir=C:\Workspace\Fonts\Windows\

set SysFontsDir=C:\Windows\Fonts\

del %SysFontsDir%arial.ttf
del %SysFontsDir%ariblk.ttf
del %SysFontsDir%ariali.ttf
del %SysFontsDir%bahnschrift.ttf
del %SysFontsDir%BIZ-UDGothicR.ttc
del %SysFontsDir%BIZ-UDGothicB.ttc
del %SysFontsDir%BIZ-UDMinchoM.ttc
del %SysFontsDir%calibri.ttf
del %SysFontsDir%calibrib.ttf
del %SysFontsDir%calibriz.ttf
del %SysFontsDir%calibrii.ttf
del %SysFontsDir%calibril.ttf
del %SysFontsDir%calibrili.ttf
del %SysFontsDir%cambria.ttc
del %SysFontsDir%cambriab.ttf
del %SysFontsDir%cambriaz.ttf
del %SysFontsDir%cambriai.ttf
del %SysFontsDir%candara.ttf
del %SysFontsDir%candarab.ttf
del %SysFontsDir%candaraz.ttf
del %SysFontsDir%candarai.ttf
del %SysFontsDir%candaral.ttf
del %SysFontsDir%candarali.ttf
del %SysFontsDir%comic.ttf
del %SysFontsDir%comicbd.ttf
del %SysFontsDir%comicz.ttf
del %SysFontsDir%comici.ttf
del %SysFontsDir%consola.ttf
del %SysFontsDir%consolai.ttf
del %SysFontsDir%constan.ttf
del %SysFontsDir%constanb.ttf
del %SysFontsDir%constanz.ttf
del %SysFontsDir%constani.ttf
del %SysFontsDir%corbel.ttf
del %SysFontsDir%corbelb.ttf
del %SysFontsDir%corbelz.ttf
del %SysFontsDir%corbeli.ttf
del %SysFontsDir%corbell.ttf
del %SysFontsDir%corbelli.ttf
del %SysFontsDir%cour.ttf
del %SysFontsDir%couri.ttf
del %SysFontsDir%Deng.ttf
del %SysFontsDir%Dengb.ttf
del %SysFontsDir%Dengl.ttf
del %SysFontsDir%ebrima.ttf
del %SysFontsDir%ebrimabd.ttf
del %SysFontsDir%simfang.ttf
del %SysFontsDir%framd.ttf
del %SysFontsDir%framdit.ttf
del %SysFontsDir%gadugi.ttf
del %SysFontsDir%gadugib.ttf
del %SysFontsDir%Gabriola.ttf
del %SysFontsDir%georgia.ttf
del %SysFontsDir%georgiai.ttf
del %SysFontsDir%impact.ttf
del %SysFontsDir%Inkfree.ttf
del %SysFontsDir%javatext.ttf
del %SysFontsDir%simkai.ttf
del %SysFontsDir%leelawui.ttf
del %SysFontsDir%leelauib.ttf
del %SysFontsDir%leeluisl.ttf
del %SysFontsDir%lucon.TTF
del %SysFontsDir%l_10646.ttf
del %SysFontsDir%malgun.ttf
del %SysFontsDir%malgunsl.ttf
del %SysFontsDir%meiryo.ttc
del %SysFontsDir%himalaya.ttf
del %SysFontsDir%msjh.ttc
del %SysFontsDir%msjhl.ttc
del %SysFontsDir%ntailu.ttf
del %SysFontsDir%ntailub.ttf
del %SysFontsDir%phagspa.ttf
del %SysFontsDir%phagspab.ttf
del %SysFontsDir%micross.ttf
del %SysFontsDir%taile.ttf
del %SysFontsDir%taileb.ttf
del %SysFontsDir%msyh.ttc
del %SysFontsDir%msyhl.ttc
del %SysFontsDir%msyi.ttf
del %SysFontsDir%mingliub.ttc
del %SysFontsDir%monbaiti.ttf
del %SysFontsDir%msgothic.ttc
del %SysFontsDir%msmincho.ttc
del %SysFontsDir%mvboli.ttf
del %SysFontsDir%mmrtext.ttf
del %SysFontsDir%mmrtextb.ttf
del %SysFontsDir%Nirmala.ttf
del %SysFontsDir%NirmalaB.ttf
del %SysFontsDir%NirmalaS.ttf
del %SysFontsDir%pala.ttf
del %SysFontsDir%palab.ttf
del %SysFontsDir%palabi.ttf
del %SysFontsDir%palai.ttf
del %SysFontsDir%SansSerifCollection.ttf
del %SysFontsDir%segoepr.ttf
del %SysFontsDir%segoeprb.ttf
del %SysFontsDir%segoesc.ttf
del %SysFontsDir%segoescb.ttf
del %SysFontsDir%seguihis.ttf
del %SysFontsDir%SegUIVar.ttf
del %SysFontsDir%simhei.ttf
del %SysFontsDir%simsunb.ttf
del %SysFontsDir%SitkaVF.ttf
del %SysFontsDir%SitkaVF-Italic.ttf
del %SysFontsDir%sylfaen.ttf
del %SysFontsDir%tahoma.ttf
del %SysFontsDir%times.ttf
del %SysFontsDir%timesi.ttf
del %SysFontsDir%trebuc.ttf
del %SysFontsDir%trebucbd.ttf
del %SysFontsDir%trebucbi.ttf
del %SysFontsDir%trebucit.ttf
del %SysFontsDir%UDDigiKyokashoN-B.ttc
del %SysFontsDir%UDDigiKyokashoN-R.ttc
del %SysFontsDir%YuGothB.ttc
del %SysFontsDir%YuGothL.ttc
del %SysFontsDir%YuGothM.ttc
del %SysFontsDir%YuGothR.ttc
del %SysFontsDir%yumin.ttf
del %SysFontsDir%yumindb.ttf
del %SysFontsDir%yuminl.ttf
del %SysFontsDir%verdana.ttf
del %SysFontsDir%verdanab.ttf
del %SysFontsDir%verdanaz.ttf
del %SysFontsDir%verdanai.ttf
del %SysFontsDir%Nirmala.ttc

copy /y %NewFontsDir%*.ttf %SysFontsDir%

copy /y %NewFontsDir%*.ttc %SysFontsDir%